[Whois_IP_Lookup]
display_location = field_menu
fields = source_ip, src, dest
label = Whois Lookup for ($@field_value$)
link.method = get
link.target = _blank
link.uri = https://www.whois.com/whois/$@field_value$
type = link
